In [1]:

import pandas as pd

In [10]:
data = pd.read_csv("Student-University.csv")
data.head(10)
data.describe()

34.62365962  78.02469282          0
count    99.000000    99.000000  99.000000
mean     65.957614    66.102779   0.606061
std      19.302009    18.638875   0.491108
min      30.058822    30.603263   0.000000
25%      51.297736    47.978125   0.000000
50%      67.319257    66.589353   1.000000
75%      80.234877    79.876423   1.000000
max      99.827858    98.869436   1.000000

In [11]:
x = data.iloc[:, [0,1] ].values

In [12]:
y = data.iloc[:, 2].values

In [13]:
print(x[:5, :]) # Prinitng the first 5 rows of split input data
print()
print(y[:5])   # Printing the first 5 rows of split output data
from sklearn import preprocessing

[[30.28671077 43.89499752]
 [35.84740877 72.90219803]
 [60.18259939 86.3085521 ]
 [79.03273605 75.34437644]
 [45.08327748 56.31637178]]

[0 0 1 1 0]


In [14]:

# Normalising data
norX = preprocessing.scale(x)

In [15]:

# Printing first 5 rows of Normalised data
print(norX[:5, :])

[[-1.85744578 -1.19754001]
 [-1.56789059  0.3666542 ]
 [-0.30071501  1.08958303]
 [ 0.6808443   0.49834707]
 [-1.08696289 -0.52772557]]


In [16]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold


In [17]:

foldings = KFold(n_splits = 5)


In [18]:

for train_index, test_index in foldings.split(norX):
  xtrain, xtest, ytrain, ytest = train_test_split(norX, y, train_size=0.80, test_size=0.20, random_state=0)

In [20]:
 x1 = xtrain[:, 0]
 x2 = xtrain[:, 1]


In [21]:
 b0 = 0
 b1 = 0
 b2 = 0
 epoch = 10000
 alpha = 0.001

In [24]:
while(epoch>0):
    for i in range(len(xtrain)):
      pred = b0 + b1*x1[i] + b2*x2[i]
      prediction = 1/(1 + np.exp(-pred))
      b0 = b0 + alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*1.0
      b1 = b1 + alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*x1[i]
      b2 = b2 + alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*x2[i]
    epoch = epoch - 1

In [26]:
print(b0)
print(b1)
print(b2)
x3 = xtest[:, 0]
x4 = xtest[:, 1]
print(ytest)

1.590641737857832
3.1148936955248936
2.412367982045799
[0 1 1 1 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1]


In [27]:

pred_list = []
y_pred = [0]*len(xtest)

In [28]:

for i in range(len(xtest)):
  predo = b0 + b1*x3[i] + b2*x4[i]
  y_pred[i] = np.round(1/(1 + np.exp(-predo)))
  pred_list.append(int(y_pred[i]))

In [29]:

print(pred_list)
from sklearn.metrics import accuracy_score
res = accuracy_score(ytest, y_pred)
acc = res*100
print("Accuracy in precentage:", acc, "%")

[1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1]
Accuracy in precentage: 90.0 %
